theme: jekyll-theme-minimal
title: Geração Z - Expectativas Mercado de Trabalho
description: Site parte do projeto de pesquisa 'Geração Z: expectativas e desafios na gestão'
show_downloads: false
logo: https://surveymonkey-assets.s3.amazonaws.com/survey/152105700/f8baa6b0-b28d-4248-8cc4-4775212adee4.jpg
